# Generated by Django 2.0.7 on 2019-08-09 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='supporters.Supporter')),
            ],
        ),
    ]
