# Generated by Django 2.0.7 on 2019-08-09 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supporters', '0002_supporternote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_processed', models.BooleanField(default=False)),
                ('pack_sent', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supporter_transactions', to=settings.AUTH_USER_MODEL)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='supporters.Supporter')),
            ],
        ),
        migrations.AlterField(
            model_name='supporternote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supporter_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
