# Generated by Django 2.0.7 on 2019-08-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0003_auto_20190809_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
