# Generated by Django 2.0.7 on 2019-08-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0004_auto_20190809_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='phone_home',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='phone_work',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
