# Generated by Django 2.0.7 on 2019-08-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0007_auto_20190809_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
