# Generated by Django 2.0.7 on 2019-08-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0011_auto_20190809_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
