# Generated by Django 2.0.7 on 2019-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0013_transaction_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
