# Generated by Django 2.0.7 on 2019-08-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0015_auto_20190812_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
