# Generated by Django 2.0.7 on 2019-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_comment_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='needsEncoding',
            field=models.BooleanField(default=False),
        ),
    ]
