# Generated by Django 2.2.4 on 2019-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20190210_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='digital',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
