name: Run tests

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual triggering from the Actions tab
  
jobs:
  test:
    environment: test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10 # Specify your required PostgreSQL version
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: threed
        # Ensure the container is fully healthy before starting workflow steps
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --no-build-isolation -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test --keepdb