# Generated by Django 2.0.7 on 2018-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0020_auto_20160628_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
