# Generated by Django 2.0.7 on 2018-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0021_show_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='fillin',
            field=models.BooleanField(default=False),
        ),
    ]
