# Generated by Django 2.0.7 on 2018-12-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0023_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='australianQuota',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='customQuotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='femaleQuota',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='localQuota',
            field=models.IntegerField(null=True),
        ),
    ]
