# Generated by Django 2.0.7 on 2018-12-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0025_auto_20181205_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='australianQuota',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='femaleQuota',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='localQuota',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='australianQuota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='femaleQuota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='localQuota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
