# Generated by Django 2.0.7 on 2019-01-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0026_auto_20181211_0418'),
        ('playlist', '0026_auto_20190110_2105'),
    ]

    operations = [
    ]
