# Generated by Django 2.2.24 on 2022-11-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0027_merge_20190110_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
